name: Bug Report
description: Please do not use bug reports for support issues.
title: '[Bug]: '
labels: ['status:not-yet-viewed', 'bug']
assignees: 'meisnate12'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT!**
        Please use [Kometa Discord](https://metamanager.wiki/en/latest/discord/) and post your question under the `kometa-help` channel for support issues.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true